FROM maven:3.9-eclipse-temurin-17-alpine

WORKDIR /app

# Copy the pom.xml file
COPY pom.xml .

# Download all required dependencies into one layer
RUN mvn dependency:go-offline -B

# Copy source code
COPY src ./src

# Copy the mvnw files for convenience
COPY mvnw .
COPY .mvn ./.mvn
RUN chmod +x mvnw

EXPOSE 8080

CMD ["./mvnw", "spring-boot:run", "-Dspring-boot.run.profiles=dev"]